[package]
name = "loader"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
engine = { path = "../engine" }
symphonia = { version = "0.5.4", features = ["all"] }
rubato = "0.15"
wave = { path = "../wave" }

[dev-dependencies]
tempfile = "3"
wave = { path = "../wave" }
