[package]
name = "tui"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
ratatui = "0.30"
input = { path = "../input" }
engine = { path = "../engine" }
ratatui-image = { version = "11", default-features = false, features = ["crossterm"] }
image = { version = "0.25", default-features = false }
wave = { path = "../wave" }
